server:
  port: 8083

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5435/transactiondb
    username: transaction_user
    password: transaction_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: transferRequested:com.banktransfer.transaction_service.event.TransferRequestedEvent,depositRequested:com.banktransfer.transaction_service.event.DepositRequestedEvent
    consumer:
      group-id: transaction-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.banktransfer.transaction_service.event"
        spring.json.type.mapping: transferRequested:com.banktransfer.transaction_service.event.TransferRequestedEvent,depositRequested:com.banktransfer.transaction_service.event.DepositRequestedEvent,balanceResult:com.banktransfer.transaction_service.event.BalanceReservationResultEvent,depositResult:com.banktransfer.transaction_service.event.DepositResultEvent