server:
  port: 8082

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5434/accountdb
    username: account_user
    password: account_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: balanceResult:com.banktransfer.account_service.event.BalanceReservationResultEvent,depositResult:com.banktransfer.account_service.event.DepositResultEvent
    consumer:
      group-id: account-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.banktransfer.account_service.event"
        spring.json.type.mapping: transferRequested:com.banktransfer.account_service.event.TransferRequestedEvent,balanceResult:com.banktransfer.account_service.event.BalanceReservationResultEvent,depositRequested:com.banktransfer.account_service.event.DepositRequestedEvent
